name: Datamax Java Spring Boot Maven Build

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
 test:
   name: Test
   runs-on: ubuntu-latest

   services:
     mysql:
       image: mysql:8.0
       env:
         MYSQL_DATABASE: datamax_db
         MYSQL_ROOT_PASSWORD: password@123
       ports:
         - 3306:3306
       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

   steps:
   - name: Checkout Repository
     uses: actions/checkout@v4

   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven

   - name: Run Maven tests
     run: mvn --batch-mode test

 build:
   name: Build
   runs-on: ubuntu-latest

   services:
     mysql:
       image: mysql:8.0
       env:
         MYSQL_DATABASE: datamax_db
         MYSQL_ROOT_PASSWORD: password@123
       ports:
         - 3306:3306
       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

   needs: test

   steps:
   - name: Checkout Repository
     uses: actions/checkout@v4

   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven

   - name: Build with Maven
     run: mvn --batch-mode package

   - name: Upload JAR artifact
     uses: actions/upload-artifact@v4
     with:
       name: datamaxbackend
       path: target/*.jar
